# cmds = {
#     'query_comm_temp_unit':':UNIT:TEMPERATURE?',
#     'set_comm_unit_f':':UNIT:TEMPERATURE F',
#     'set_comm_unit_c':':UNIT:TEMPERATURE C',
#     'query_temp_disp':':UNIT:TEMPERATURE:DISPLAY?',
#     'set_disp_unit_f':':UNIT:TEMPERATURE:DISPLAY F',
#     'set_disp_unit_c':':UNIT:TEMPERATURE:DISPLAY C',
#     'read_temp_pv':':SOURCE:CLOOP#:PVALUE?',
#     'query_input_err':':SOURCE:CLOOP{}:ERROR?',
#     'read_s_point':':SOURCE:CLOOP{}:SPOINT?',
#     'write_s_pount':':SOURCE:CLOOP{}:SPOINT {}',
#     '':':SOURCE:CLOOP#:IDLE?',
#     '':':SOURCE:CLOOP#:IDLE <value>',
#     '':':SOURCE:CASCADE1:SPOINT?',
#     '':':SOURCE:CASCADE1:SPOINT <value>',
#     '':':SOURCE:CASCADE1:OUTER:PVALUE?',
#     '':':SOURCE:CASCADE1:OUTER:ERROR?',
#     '':':SOURCE:CASCADE1:INNER:PVALUE?<floating point value>',
#     '':':SOURCE:CASCADE1:INNER:ERROR?',
#     '':':SOURCE:CASCADE1:OUTER:SPOINT?',
#     '':':SOURCE:CASCADE1:INNER:SPOINT?',
#     '':':SOURCE:CLOOP#:RACTION OFF',
#     '':':SOURCE:CLOOP#:RACTION STARTUP',
#     '':':SOURCE:CLOOP#:RACTION SETPOINT',
#     '':':SOURCE:CLOOP#:RACTION BOTH',
#     '':':SOURCE:CLOOP#:RSCALE MINUTES',
#     '':':SOURCE:CLOOP#:RSCALE HOURS',
#     '':':SOURCE:CLOOP#:RRATE?',
#     '':':SOURCE:CLOOP#:RTIME?',
#     '':':SOURCE:CLOOP#:RRATE <value>',
#     '':':SOURCE:CLOOP#:RTIME <value>',
#     '':':OUTPUT#:STATE ON',
#     '':':OUTPUT#:STATE OFF',
#     '':':OUTPUT#:STATE?',
#     '':':PROGRAM:NUMBER <value>',
#     'query_prog_name':':PROGRAM:NAME?',
#     'sel_prog_step':':PROGRAM:STEP <value>',
#     '':':PROGRAM:SELECTED:STATE START',
#     '':':PROGRAM:SELECTED:STATE STOP',
#     '':':PROGRAM:SELECTED:STATE PAUSE',
#     '':':PROGRAM:SELECTED:STATE RESUME',
#     'identify':'*IDN?',
#     }